name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: [1.15]
    name: ${{ matrix.os }} @ Go ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: golang set up
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: checkout code
        uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}

      - name: vet
        run: go vet ./...

      - name: build
        run: go build ./...

      - name: test
        run: go test -race ./...

      - name: generate coverage report
        run: make gen-coverage

      - name: push coverage report
        if: success() && matrix.go == 1.15 && matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v1
        with:
          token: 30aaf07c-66b2-4d4c-96ac-9802c9a487f4
          file: ./coverage.txt
          fail_ci_if_error: true
